version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev:auth
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - ${AUTH_PORT}:${HTTP_PORT}
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app

  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
      target: development
    command: npm run start:dev:user
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - ${USER_PORT}:${HTTP_PORT}
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app

  crud:
    build:
      context: .
      dockerfile: ./apps/crud/Dockerfile
      target: development
    command: npm run start:dev:crud
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - ${CRUD_PORT}:${HTTP_PORT}
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
volumes:
  postgres-data:
